(function() {var implementors = {};
implementors["cranelift_codegen"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"cranelift_codegen/isa/enum.LookupError.html\" title=\"enum cranelift_codegen::isa::LookupError\">LookupError</a>",synthetic:false,types:["cranelift_codegen::isa::LookupError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"cranelift_codegen/settings/enum.SetError.html\" title=\"enum cranelift_codegen::settings::SetError\">SetError</a>",synthetic:false,types:["cranelift_codegen::settings::SetError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"cranelift_codegen/verifier/struct.VerifierError.html\" title=\"struct cranelift_codegen::verifier::VerifierError\">VerifierError</a>",synthetic:false,types:["cranelift_codegen::verifier::VerifierError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"cranelift_codegen/verifier/struct.VerifierErrors.html\" title=\"struct cranelift_codegen::verifier::VerifierErrors\">VerifierErrors</a>",synthetic:false,types:["cranelift_codegen::verifier::VerifierErrors"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"cranelift_codegen/enum.CodegenError.html\" title=\"enum cranelift_codegen::CodegenError\">CodegenError</a>",synthetic:false,types:["cranelift_codegen::result::CodegenError"]},];
implementors["cranelift_wasm"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"cranelift_wasm/enum.WasmError.html\" title=\"enum cranelift_wasm::WasmError\">WasmError</a>",synthetic:false,types:["cranelift_wasm::environ::spec::WasmError"]},];
implementors["faerie"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"faerie/artifact/enum.ArtifactError.html\" title=\"enum faerie::artifact::ArtifactError\">ArtifactError</a>",synthetic:false,types:["faerie::artifact::ArtifactError"]},];
implementors["failure"] = [];
implementors["target_lexicon"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"target_lexicon/enum.ParseError.html\" title=\"enum target_lexicon::ParseError\">ParseError</a>",synthetic:false,types:["target_lexicon::parse_error::ParseError"]},];
implementors["wasmtime_api"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"wasmtime_api/struct.Trap.html\" title=\"struct wasmtime_api::Trap\">Trap</a>",synthetic:false,types:["wasmtime_api::trap::Trap"]},];
implementors["wasmtime_environ"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"wasmtime_environ/enum.CompileError.html\" title=\"enum wasmtime_environ::CompileError\">CompileError</a>",synthetic:false,types:["wasmtime_environ::compilation::CompileError"]},];
implementors["wasmtime_jit"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"wasmtime_jit/enum.ActionError.html\" title=\"enum wasmtime_jit::ActionError\">ActionError</a>",synthetic:false,types:["wasmtime_jit::action::ActionError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"wasmtime_jit/struct.UnknownInstance.html\" title=\"struct wasmtime_jit::UnknownInstance\">UnknownInstance</a>",synthetic:false,types:["wasmtime_jit::context::UnknownInstance"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"wasmtime_jit/enum.ContextError.html\" title=\"enum wasmtime_jit::ContextError\">ContextError</a>",synthetic:false,types:["wasmtime_jit::context::ContextError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"wasmtime_jit/enum.SetupError.html\" title=\"enum wasmtime_jit::SetupError\">SetupError</a>",synthetic:false,types:["wasmtime_jit::instantiate::SetupError"]},];
implementors["wasmtime_runtime"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"wasmtime_runtime/struct.LinkError.html\" title=\"struct wasmtime_runtime::LinkError\">LinkError</a>",synthetic:false,types:["wasmtime_runtime::instance::LinkError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"wasmtime_runtime/enum.InstantiationError.html\" title=\"enum wasmtime_runtime::InstantiationError\">InstantiationError</a>",synthetic:false,types:["wasmtime_runtime::instance::InstantiationError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
